### ISSUE TITLE
KHM uncommon lands

### ISSUE THREAD

**Issue by dpdearing** [mtgoncurve/landlord#33]
The [uncommon lands in Kaldheim](https://scryfall.com/search?as=grid&order=name&q=type%3Aland+set%3Akhm+rarity%3Au) (for example, `Surtland Frostpyre`) do not produce two colors of mana, but landlord seems to think that they do.  They *do* have an activated cost that requires two colors, but they only produce one color.

<img width="925" alt="Screen Shot 2021-02-08 at 8 58 43 PM" src="https://user-images.githubusercontent.com/2936189/107317949-7ce14c80-6a50-11eb-845d-c0f11c4427eb.png">

**Comment by jshrake** [comment]
Thanks for the report! I'll deploy the updated package to the site soon.
